rest.address.base=ignore
rest.address.test=ignore
ssl.trustAll=ignore
rest.basic.username=ignore
rest.basic.password=ignore
rest.token.value=ignore
rest.token.name=ignore
rest.token.jwt.algorithm=ignore
rest.token.jwt.secret=ignore
rest.token.jwt.secretBase64=ignore
rest.token.jwt.payload=ignore
rest.token.jwt.location=ignore
rest.apikey.value=ignore
rest.apikey.name=ignore
rest.apikey.location=ignore
rest.oauth2.tokenUrl=ignore
rest.oauth2.clientId=ignore
rest.oauth2.clientSecret=ignore
rest.oauth2.privateKey=ignore
rest.oauth2.scope=ignore
rest.oauth2.audience=ignore
rest.oauth2.tokenName=ignore
rest.oauth2.clientAuthenticationScheme=ignore
rest.oauth2.username=ignore
rest.oauth2.password=ignore
rest.oauth2.issuer=ignore
rest.oauth2.keyId=ignore
rest.oauth2.algorithm=ignore
rest.oauth2.subject=ignore
rest.digest.username=ignore
rest.digest.password=ignore
rest.digest.autoChallenge=ignore
rest.digest.maxRetries=ignore
rest.digest.preemptiveAuth=ignore
rest.digest.algorithmPreference=ignore
rest.digest.stateCacheEnabled=ignore
rest.hawk.id=ignore
rest.hawk.key=ignore
rest.hawk.algorithm=ignore
rest.hawk.includePayloadHash=ignore
rest.hawk.offset=ignore
rest.hawk.ext=ignore
rest.aws.accessKey=ignore
rest.aws.secretKey=ignore
rest.aws.sessionToken=ignore
rest.aws.region=ignore
rest.aws.service=ignore
rest.aws.signatureVersion=ignore
rest.ntlm.username=ignore
rest.ntlm.password=ignore
rest.ntlm.domain=ignore
rest.ntlm.workstation=ignore
rest.ntlm.version=ignore